[versions]
velocityApi = "3.4.0-SNAPSHOT"
shadow = "9.3.0"
cloud = "1.8.4"
vanishBridge = "2.0-SNAPSHOT"
configme = "1.4.1"
platformDetection="2.2"
proxyDiscordApi="1.2"
prometheusExporter = "3.0-SNAPSHOT"
prometheus = "1.4.3"

[libraries]
velocityApi = { group = "com.velocitypowered", name = "velocity-api", version.ref="velocityApi" }
cloudVelocity = { group = "cloud.commandframework", name = "cloud-velocity", version.ref="cloud" }
cloudMinecraftExtras = { group = "cloud.commandframework", name = "cloud-minecraft-extras", version.ref="cloud" }
cloudAnnotations = { group = "cloud.commandframework", name = "cloud-annotations", version.ref="cloud" }
vanishBridgeHelper = { group = "uk.co.notnull", name = "VanishBridge-helper", version.ref="vanishBridge" }
configMe = { group = "ch.jalu", name = "configme", version.ref="configme" }
platformDetection = { group = "uk.co.notnull", name = "PlatformDetection-velocity", version.ref="platformDetection" }
proxyDiscordApi = { group = "uk.co.notnull", name = "ProxyDiscordAPI", version.ref="proxyDiscordApi" }
prometheusExporter =  { group = "uk.co.notnull", name = "MinecraftPrometheusExporter-velocity", version.ref  = "prometheusExporter" }
prometheusCore = { group = "io.prometheus", name = "prometheus-metrics-core", version.ref="prometheus" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
